### PR TITLE
Adding support for input help text via '?'

### PR DESCRIPTION
**Pull request by GreenGremlin**
This change allows a user to enter "?" at an input prompt and sprinter will print further help text.

### CODE REVIEW

**Comment by toumorokoshi** [comment]
I fixed the unit tests recently, so they should be working. I can't accept any PRs that break the tests.

**Comment by GreenGremlin** [comment]
Oh, nice! I'll check out the failures.

**Comment by GreenGremlin** [comment]
I can't seem to get the unit tests to pass locally, even on branches that are passing on travis. Any tips on getting them to work?

**Comment by GreenGremlin** [comment]
I've tried running them as `./uranium test` and `./bin/py.test`.

**Comment by toumorokoshi** [comment]
@GreenGremlin can you post a traceback? you can also try activating the virtualenv by running:

    source bin/activate

first. That's what's typically required to get the dependencies to be imported.

**Comment by toumorokoshi** [comment]
thanks!

**Comment by GreenGremlin** [comment]
Thank you!

**Pull request merged**
